### ISSUE TITLE
stripe js not happy

### ISSUE THREAD

**Issue by jasonfb** [hotwired/turbo-rails#167]
this is an issue with `stripe-rails` gem — probably needs fixing in  `stripe-rails` (will cross-post when I am finished leaving notes here)

```
Started PUT "/dashboard/get_emails_imports/120" for 127.0.0.1 at 2021-04-20 11:44:55 -0400
Processing by Dashboard::GetEmailsImportsController#update as TURBO_STREAM
  Parameters: {"authenticity_token"=>"SwTPgpd47KvMsIZqi65UpTE0fUPRyRJB8qa8xwO0VYEN27E5wA6Hr9foB+3pFEeTMRGD+sNOc7Ek7xrXaV38Iw==", "get_emails_import"=>{"_action"=>"accept"}, "commit"=>"Accept", "id"=>"120"}
  Account Load (0.3ms)  SELECT `accounts`.* FROM `accounts` WHERE `accounts`.`deleted_at` IS NULL AND `accounts`.`id` = 1 ORDER BY `accounts`.`id` ASC LIMIT 1
  ↳ app/controllers/application_controller.rb:24:in `block in <class:ApplicationController>'
  GetEmailsImport Load (0.2ms)  SELECT `get_emails_imports`.* FROM `get_emails_imports` WHERE `get_emails_imports`.`id` = 120 LIMIT 1
  ↳ app/controllers/dashboard/get_emails_imports_controller.rb:10:in `load_get_emails_import'
  GetEmailsRule Load (0.2ms)  SELECT `get_emails_rules`.* FROM `get_emails_rules` WHERE `get_emails_rules`.`id` = 4 LIMIT 1
  ↳ app/controllers/dashboard/get_emails_imports_controller.rb:11:in `load_get_emails_import'
  GetEmailsHook Load (0.3ms)  SELECT `get_emails_hooks`.* FROM `get_emails_hooks` WHERE `get_emails_hooks`.`id` = 1 LIMIT 1
  ↳ app/controllers/dashboard/get_emails_imports_controller.rb:11:in `load_get_emails_import'
  Account Load (0.3ms)  SELECT `accounts`.* FROM `accounts` WHERE `accounts`.`deleted_at` IS NULL AND `accounts`.`id` = 1 LIMIT 1
  ↳ app/controllers/dashboard/get_emails_imports_controller.rb:11:in `load_get_emails_import'
  Crusade Load (0.4ms)  SELECT `crusades`.* FROM `crusades` WHERE `crusades`.`id` = 2 LIMIT 1
  ↳ app/models/get_emails_import.rb:7:in `accept!'
  Target Load (0.3ms)  SELECT `targets`.* FROM `targets` WHERE `targets`.`account_id` = 1 AND `targets`.`email` = 'tman5235@gmail.com' LIMIT 1
  ↳ app/models/get_emails_import.rb:9:in `accept!'
  TRANSACTION (0.1ms)  BEGIN
  ↳ app/models/get_emails_import.rb:12:in `accept!'
  Target Exists? (0.3ms)  SELECT 1 AS one FROM `targets` WHERE `targets`.`email` = 'tman5235@gmail.com' AND `targets`.`account_id` = 1 LIMIT 1
  ↳ app/models/get_emails_import.rb:12:in `accept!'
  BlacklistedDomain Exists? (0.4ms)  SELECT 1 AS one FROM `blacklisted_domains` WHERE `blacklisted_domains`.`domain` = 'gmail.com' LIMIT 1
  ↳ app/models/blacklisted_domain.rb:9:in `is_blacklisted'
  Target Create (1.1ms)  INSERT INTO `targets` (`email`, `account_id`, `first`, `last`, `created_at`, `updated_at`, `original_source`) VALUES ('*****', 1, '****', '*****', '2021-04-20 15:44:55.291317', '2021-04-20 15:44:55.291317', 'getemails')
  ↳ app/models/get_emails_import.rb:12:in `accept!'
  TRANSACTION (1.2ms)  COMMIT
  ↳ app/models/get_emails_import.rb:12:in `accept!'
  Temperature Load (0.4ms)  SELECT `temperatures`.* FROM `temperatures` WHERE `temperatures`.`name` = 'hot' LIMIT 1
  ↳ app/models/temperature.rb:18:in `HOT'
  Temperature Load (0.2ms)  SELECT `temperatures`.* FROM `temperatures` WHERE `temperatures`.`name` = 'warm' LIMIT 1
  ↳ app/models/temperature.rb:10:in `WARM'
  Temperature Load (0.2ms)  SELECT `temperatures`.* FROM `temperatures` WHERE `temperatures`.`name` = 'cold' LIMIT 1
  ↳ app/models/temperature.rb:14:in `COLD'
  Temperature Load (0.1ms)  SELECT `temperatures`.* FROM `temperatures` WHERE `temperatures`.`name` = 'frost' LIMIT 1
  ↳ app/models/temperature.rb:22:in `FROST'
  CACHE Temperature Load (0.0ms)  SELECT `temperatures`.* FROM `temperatures` WHERE `temperatures`.`name` = 'hot' LIMIT 1
  ↳ app/models/temperature.rb:18:in `HOT'
  CACHE Temperature Load (0.0ms)  SELECT `temperatures`.* FROM `temperatures` WHERE `temperatures`.`name` = 'warm' LIMIT 1
  ↳ app/models/temperature.rb:10:in `WARM'
  CACHE Temperature Load (0.0ms)  SELECT `temperatures`.* FROM `temperatures` WHERE `temperatures`.`name` = 'cold' LIMIT 1
  ↳ app/models/temperature.rb:14:in `COLD'
  CACHE Temperature Load (0.0ms)  SELECT `temperatures`.* FROM `temperatures` WHERE `temperatures`.`name` = 'frost' LIMIT 1
  ↳ app/models/temperature.rb:22:in `FROST'
  CACHE Temperature Load (0.0ms)  SELECT `temperatures`.* FROM `temperatures` WHERE `temperatures`.`name` = 'hot' LIMIT 1
  ↳ app/models/temperature.rb:18:in `HOT'
  CACHE Temperature Load (0.0ms)  SELECT `temperatures`.* FROM `temperatures` WHERE `temperatures`.`name` = 'warm' LIMIT 1
  ↳ app/models/temperature.rb:10:in `WARM'
  CACHE Temperature Load (0.0ms)  SELECT `temperatures`.* FROM `temperatures` WHERE `temperatures`.`name` = 'cold' LIMIT 1
  ↳ app/models/temperature.rb:14:in `COLD'
  CACHE Temperature Load (0.0ms)  SELECT `temperatures`.* FROM `temperatures` WHERE `temperatures`.`name` = 'frost' LIMIT 1
  ↳ app/models/temperature.rb:22:in `FROST'
  CACHE Temperature Load (0.0ms)  SELECT `temperatures`.* FROM `temperatures` WHERE `temperatures`.`name` = 'hot' LIMIT 1
  ↳ app/models/temperature.rb:18:in `HOT'
  CACHE Temperature Load (0.0ms)  SELECT `temperatures`.* FROM `temperatures` WHERE `temperatures`.`name` = 'warm' LIMIT 1
  ↳ app/models/temperature.rb:10:in `WARM'
  CACHE Temperature Load (0.0ms)  SELECT `temperatures`.* FROM `temperatures` WHERE `temperatures`.`name` = 'cold' LIMIT 1
  ↳ app/models/temperature.rb:14:in `COLD'
  CACHE Temperature Load (0.0ms)  SELECT `temperatures`.* FROM `temperatures` WHERE `temperatures`.`name` = 'frost' LIMIT 1
  ↳ app/models/temperature.rb:22:in `FROST'
  CrusadeTarget Load (0.4ms)  SELECT `crusade_targets`.* FROM `crusade_targets` WHERE `crusade_targets`.`crusade_id` = 2 AND `crusade_targets`.`target_id` = 1675 LIMIT 1
  ↳ app/models/get_emails_import.rb:18:in `accept!'
  CACHE Temperature Load (0.0ms)  SELECT `temperatures`.* FROM `temperatures` WHERE `temperatures`.`name` = 'cold' LIMIT 1
  ↳ app/models/temperature.rb:14:in `COLD'
  TRANSACTION (0.1ms)  BEGIN
  ↳ app/models/get_emails_import.rb:21:in `accept!'
  CrusadeTarget Create (0.4ms)  INSERT INTO `crusade_targets` (`crusade_id`, `target_id`, `temperature_id`, `created_at`, `updated_at`) VALUES (2, 1675, 3, '2021-04-20 15:44:55.327427', '2021-04-20 15:44:55.327427')
  ↳ app/models/get_emails_import.rb:21:in `accept!'
  Crusade Update All (0.4ms)  UPDATE `crusades` SET `crusades`.`_cold_active_count` = COALESCE(`crusades`.`_cold_active_count`, 0) + 1 WHERE `crusades`.`id` = 2
  ↳ app/models/get_emails_import.rb:21:in `accept!'
  Crusade Update All (0.2ms)  UPDATE `crusades` SET `crusades`.`_active` = COALESCE(`crusades`.`_active`, 0) + 1 WHERE `crusades`.`id` = 2
  ↳ app/models/get_emails_import.rb:21:in `accept!'
  Crusade Update All (0.2ms)  UPDATE `crusades` SET `crusades`.`_cold` = COALESCE(`crusades`.`_cold`, 0) + 1 WHERE `crusades`.`id` = 2
  ↳ app/models/get_emails_import.rb:21:in `accept!'
  CrusadeTarget Update (0.4ms)  UPDATE `crusade_targets` SET `crusade_targets`.`unsubscribe_nonce` = 'kmbeikzafmkgpwephbrt' WHERE `crusade_targets`.`id` = 2500
  ↳ app/models/crusade_target.rb:88:in `check_unsubscribe_nonce'
  TRANSACTION (0.8ms)  COMMIT
  ↳ app/models/get_emails_import.rb:21:in `accept!'
  TRANSACTION (0.2ms)  BEGIN
  ↳ app/models/get_emails_import.rb:24:in `accept!'
  GetEmailsImport Update (1.1ms)  UPDATE `get_emails_imports` SET `get_emails_imports`.`accepted_at` = '2021-04-20 15:44:55' WHERE `get_emails_imports`.`id` = 120
  ↳ app/models/get_emails_import.rb:24:in `accept!'
  TRANSACTION (1.0ms)  COMMIT
  ↳ app/models/get_emails_import.rb:24:in `accept!'
  Rendering layout layouts/application-dashboard.haml
  Rendering dashboard/get_emails_imports/update.turbo_stream.haml within layouts/application-dashboard
  Rendered dashboard/get_emails_imports/update.turbo_stream.haml within layouts/application-dashboard (Duration: 0.2ms | Allocations: 122)
[Webpacker] Everything's up-to-date. Nothing to do
[Webpacker] Everything's up-to-date. Nothing to do
  Rendered layout layouts/application-dashboard.haml (Duration: 18.0ms | Allocations: 25816)
Completed 500 Internal Server Error in 102ms (ActiveRecord: 17.8ms | Allocations: 78553)


  
ActionView::Template::Error (Missing partial stripe/_js with {:locale=>[:en], :formats=>[:turbo_stream], :variants=>[], :handlers=>[:raw, :erb, :html, :builder, :ruby, :jbuilder, :haml]}. Searched in:
  * "/Users/jason/Work/Verso_Commerce/verso-commerce/app/views"
  * "/Users/jason/Work/hot-glue/app/views"
  * "/Users/jason/.rvm/gems/ruby-2.6.6/gems/stripe-rails-2.3.0/app/views"
  * "/Users/jason/.rvm/gems/ruby-2.6.6/gems/kaminari-core-1.2.1/app/views"
  * "/Users/jason/.rvm/gems/ruby-2.6.6/gems/devise-4.7.3/app/views"
  * "/Users/jason/.rvm/gems/ruby-2.6.6/gems/actiontext-6.1.3.1/app/views"
  * "/Users/jason/.rvm/gems/ruby-2.6.6/gems/actionmailbox-6.1.3.1/app/views"
):
    42:       gtag('config', 'UA-158667596-1');
    43: 
    44: 
    45:     = stripe_javascript_tag
    46: 
    47:     :javascript
    48:       VERSO.__stripe_pk = "#{Rails.configuration.stripe.publishable_key}"
  
app/views/layouts/application-dashboard.haml:45
** [Honeybadger] Unable to send error report: API key is missing. id=a40cc169-772f-4e7e-9bd3-37651a9b3b6e level=3 pid=80216

```

I think it looks to me like Turbo is doing its thing correctly but the helper `stripe_javascript_tag` is failing because the format is `:turbo_stream`

**Comment by jasonfb** [comment]
this seems intermittent. I commented out stripe_javascript_tag, the symptom went away, then I uncommented stripe_javascript_tag again but the symptom did not come back... very strange

**Comment by uurcank** [comment]
@jasonfb   for stripe implementation check [pay gem](https://github.com/pay-rails/pay) It works well with turbo

You may want to move this issue to the stripe-rails repo and close it here. Looks like gem injects a partial and there is a bug there.
