### ISSUE TITLE
flash doesn't work with form but works with link even it's the same redirection

### ISSUE THREAD

**Issue by MatthieuHernandez** [hotwired/turbo-rails#193]
I have this code:

_articles/show.html.erb_
```erb
<%= turbo_frame_tag 'id_1' do %>
    <!--> some code <-->
    <%= form_with scope: :note, url: notes_path(article_id: @article.id) do |form| %>
        <!--> the form <-->
    <%= form.submit %>
    <!--> some code <-->
    <%= link_to 'Delete', note_path(article_id: article_id, id: note.id), method: :delete, data: { confirm: 'Are you sure you want to delete this note?' } %>
<% end %>
```

_notes_controller.rb_
```rb
class NotesController < ApplicationController

    def create
        if note_params[:note_text].blank?
            flash[:danger] = "The note can't be empty."
        else
            # some code
            @note.save
            flash[:success] = "Note saved"
        end
        redirect_to article_path(params[:article_id])
    end

    def destroy
        @note = Note.find(params[:id])
        @note.destroy
        flash[:success] = "Note deleted"
        redirect_to article_path(id: params[:article_id], query: params[:query])
    end
end
```

When I delete a note, turbo correctly displays the flash without reload the whole page.
When I created a note, the flash is not displayed but turbo correctly add the new note to the page.
Can you explain me this ?

This is really weird 🤔 

In addition, the server logs are the same in both cases:
```
Started GET "/articles/45" for ::1 at 2021-06-26 18:30:51 +0200
Processing by ArticlesController#show as TURBO_STREAM
  Parameters: {"id"=>"45"}
  Article Load (0.3ms)  SELECT "articles".* FROM "articles" WHERE "articles"."id" = $1 LIMIT $2  [["id", 45], ["LIMIT", 1]]
  ↳ app/controllers/articles_controller.rb:49:in `show'
  User Load (0.5ms)  SELECT "users".* FROM "users" WHERE "users"."id" = $1 LIMIT $2  [["id", 10], ["LIMIT", 1]]
  ↳ app/helpers/sessions_helper.rb:15:in `current_user'
  Note Load (1.3ms)
```

Please help me it's driving me crazy several hours trying to figure it out !

**Comment by MatthieuHernandez** [comment]
Also I have **rails-ujs** include to project, I don't really know what it is for but I saw that it could cause problems...

**Comment by MatthieuHernandez** [comment]
The problem wasn't turbo, I solve the probleme by adding `local: true` in the `form_with`:
```erb
<%= form_with scope: :note, url: notes_path(article_id: @article.id), local: true do |form| %>
```
I believe that the problem came from UJS which prevented the redirection, not sure how or why.
