### ISSUE TITLE
"Request forgery protection requires a working session store" when model has a "belongs_to" association

### ISSUE THREAD

**Issue by pettersj** [hotwired/turbo-rails#241]
New rails app from master (both on alpha2 release and alpha2 +30 commits). Tested on ruby 2.7.2 and 3.0.2. turbo_rails 0.7.14.
`rails new alpha -j esbuild --css=tailwind -d postgresql --dev` 

This works as expected:
` models/form.rb`
```
class Form < ApplicationRecord
  has_many :question_groups
  has_many :questions
  
  after_create_commit :append_to_list

  def append_to_list
   # appends to a list of forms
    broadcast_append_to :forms
  end
end
```

But this throws an error. 
Same error whether I create a new from the app or from the console.
`models/question.rb`
```
class Question < ApplicationRecord
  belongs_to :form

  after_create_commit :append_to_form

  def append_to_form
    # appends to the forms list of questions
    broadcast_append_later_to :questions, partial: 'questions/form'
  end

end
```

Error:
```
Error performing Turbo::Streams::ActionBroadcastJob: ActionView::Template::Error (Request forgery protection requires a working session store but your application has sessions disabled. You need to either disable request forgery protection, or configure a working session store.)
```
Also tested with a model called QuestionGroup.

full trace:
```
15:59:32 web.1  | [ActiveJob] [Turbo::Streams::ActionBroadcastJob] [02114351-89cb-4a84-82a6-67340ec88ced] Performing Turbo::Streams::ActionBroadcastJob (Job ID: 02114351-89cb-4a84-82a6-67340ec88ced) from Async(default) enqueued at 2021-09-20T13:59:32Z with arguments: "questions", {:action=>:append, :target=>"questions", :targets=>nil, :partial=>"questions/form", :locals=>{:question=>#<GlobalID:0x00007fc1b9271320 @uri=#<URI::GID gid://mapping/Question/12>>}}
15:59:32 web.1  | [ActiveJob] [Turbo::Streams::ActionBroadcastJob] [02114351-89cb-4a84-82a6-67340ec88ced]   Rendered questions/_form.html.erb (Duration: 1.3ms | Allocations: 1066)
15:59:32 web.1  | [ActiveJob] [Turbo::Streams::ActionBroadcastJob] [02114351-89cb-4a84-82a6-67340ec88ced] Error performing Turbo::Streams::ActionBroadcastJob (Job ID: 02114351-89cb-4a84-82a6-67340ec88ced) from Async(default) in 4.7ms: ActionView::Template::Error (Request forgery protection requires a working session store but your application has sessions disabled. You need to either disable request forgery protection, or configure a working session store.):
15:59:32 web.1  | /Users/petter/.rvm/gems/ruby-3.0.2/bundler/gems/rails-780753f571d2/actionpack/lib/action_controller/metal/request_forgery_protection.rb:483:in `ensure_session_is_enabled!'
15:59:32 web.1  | /Users/petter/.rvm/gems/ruby-3.0.2/bundler/gems/rails-780753f571d2/actionpack/lib/action_controller/metal/request_forgery_protection.rb:472:in `protect_against_forgery?'
15:59:32 web.1  | /Users/petter/.rvm/gems/ruby-3.0.2/bundler/gems/rails-780753f571d2/actionpack/lib/action_controller/metal/request_forgery_protection.rb:115:in `protect_against_forgery?'
15:59:32 web.1  | /Users/petter/.rvm/gems/ruby-3.0.2/bundler/gems/rails-780753f571d2/actionview/lib/action_view/helpers/url_helper.rb:753:in `token_tag'
15:59:32 web.1  | /Users/petter/.rvm/gems/ruby-3.0.2/bundler/gems/rails-780753f571d2/actionview/lib/action_view/helpers/form_tag_helper.rb:913:in `extra_tags_for_form'
15:59:32 web.1  | /Users/petter/.rvm/gems/ruby-3.0.2/bundler/gems/rails-780753f571d2/actionview/lib/action_view/helpers/form_tag_helper.rb:927:in `form_tag_html'
15:59:32 web.1  | /Users/petter/.rvm/gems/ruby-3.0.2/bundler/gems/rails-780753f571d2/actionview/lib/action_view/helpers/form_tag_helper.rb:932:in `form_tag_with_body'
15:59:32 web.1  | /Users/petter/.rvm/gems/ruby-3.0.2/bundler/gems/rails-780753f571d2/actionview/lib/action_view/helpers/form_helper.rb:759:in `form_with'
15:59:32 web.1  | /Users/petter/projects/rails/mapping/app/views/questions/_form.html.erb:2:in `_app_views_questions__form_html_erb__1453197594147602736_121620'
15:59:32 web.1  | /Users/petter/.rvm/gems/ruby-3.0.2/bundler/gems/rails-780753f571d2/actionview/lib/action_view/base.rb:247:in `public_send'
15:59:32 web.1  | /Users/petter/.rvm/gems/ruby-3.0.2/bundler/gems/rails-780753f571d2/actionview/lib/action_view/base.rb:247:in `_run'
15:59:32 web.1  | /Users/petter/.rvm/gems/ruby-3.0.2/bundler/gems/rails-780753f571d2/actionview/lib/action_view/template.rb:154:in `block in render'
15:59:32 web.1  | /Users/petter/.rvm/gems/ruby-3.0.2/bundler/gems/rails-780753f571d2/activesupport/lib/active_support/notifications.rb:209:in `instrument'
15:59:32 web.1  | /Users/petter/.rvm/gems/ruby-3.0.2/bundler/gems/rails-780753f571d2/actionview/lib/action_view/template.rb:354:in `instrument_render_template'
15:59:32 web.1  | /Users/petter/.rvm/gems/ruby-3.0.2/bundler/gems/rails-780753f571d2/actionview/lib/action_view/template.rb:152:in `render'
15:59:32 web.1  | /Users/petter/.rvm/gems/ruby-3.0.2/bundler/gems/rails-780753f571d2/actionview/lib/action_view/renderer/partial_renderer.rb:251:in `block in render_partial_template'
15:59:32 web.1  | /Users/petter/.rvm/gems/ruby-3.0.2/bundler/gems/rails-780753f571d2/activesupport/lib/active_support/notifications.rb:207:in `block in instrument'
15:59:32 web.1  | /Users/petter/.rvm/gems/ruby-3.0.2/bundler/gems/rails-780753f571d2/activesupport/lib/active_support/notifications/instrumenter.rb:24:in `instrument'
15:59:32 web.1  | /Users/petter/.rvm/gems/ruby-3.0.2/bundler/gems/rails-780753f571d2/activesupport/lib/active_support/notifications.rb:207:in `instrument'
15:59:32 web.1  | /Users/petter/.rvm/gems/ruby-3.0.2/bundler/gems/rails-780753f571d2/actionview/lib/action_view/renderer/partial_renderer.rb:246:in `render_partial_template'
15:59:32 web.1  | /Users/petter/.rvm/gems/ruby-3.0.2/bundler/gems/rails-780753f571d2/actionview/lib/action_view/renderer/partial_renderer.rb:237:in `render'
15:59:32 web.1  | /Users/petter/.rvm/gems/ruby-3.0.2/bundler/gems/rails-780753f571d2/actionview/lib/action_view/renderer/renderer.rb:81:in `render_partial_to_object'
15:59:32 web.1  | /Users/petter/.rvm/gems/ruby-3.0.2/bundler/gems/rails-780753f571d2/actionview/lib/action_view/renderer/renderer.rb:27:in `render_to_object'
15:59:32 web.1  | /Users/petter/.rvm/gems/ruby-3.0.2/bundler/gems/rails-780753f571d2/actionview/lib/action_view/rendering.rb:117:in `block in _render_template'
15:59:32 web.1  | /Users/petter/.rvm/gems/ruby-3.0.2/bundler/gems/rails-780753f571d2/actionview/lib/action_view/base.rb:273:in `in_rendering_context'
15:59:32 web.1  | /Users/petter/.rvm/gems/ruby-3.0.2/bundler/gems/rails-780753f571d2/actionview/lib/action_view/rendering.rb:116:in `_render_template'
15:59:32 web.1  | /Users/petter/.rvm/gems/ruby-3.0.2/bundler/gems/rails-780753f571d2/actionpack/lib/action_controller/metal/streaming.rb:216:in `_render_template'
15:59:32 web.1  | /Users/petter/.rvm/gems/ruby-3.0.2/bundler/gems/rails-780753f571d2/actionview/lib/action_view/rendering.rb:103:in `render_to_body'
15:59:32 web.1  | /Users/petter/.rvm/gems/ruby-3.0.2/bundler/gems/rails-780753f571d2/actionpack/lib/action_controller/metal/rendering.rb:46:in `render_to_body'
15:59:32 web.1  | /Users/petter/.rvm/gems/ruby-3.0.2/bundler/gems/rails-780753f571d2/actionpack/lib/action_controller/metal/renderers.rb:142:in `render_to_body'
15:59:32 web.1  | /Users/petter/.rvm/gems/ruby-3.0.2/bundler/gems/rails-780753f571d2/actionpack/lib/abstract_controller/rendering.rb:47:in `render_to_string'
15:59:32 web.1  | /Users/petter/.rvm/gems/ruby-3.0.2/bundler/gems/rails-780753f571d2/actionpack/lib/action_controller/metal/rendering.rb:35:in `render_to_string'
15:59:32 web.1  | /Users/petter/.rvm/gems/ruby-3.0.2/bundler/gems/rails-780753f571d2/actionpack/lib/action_controller/renderer.rb:100:in `render'
15:59:32 web.1  | /Users/petter/.rvm/gems/ruby-3.0.2/bundler/gems/rails-780753f571d2/actionpack/lib/action_controller/metal/rendering.rb:11:in `render'
15:59:32 web.1  | /Users/petter/.rvm/gems/ruby-3.0.2/gems/turbo-rails-0.7.14/app/channels/turbo/streams/broadcasts.rb:86:in `render_format'
15:59:32 web.1  | /Users/petter/.rvm/gems/ruby-3.0.2/gems/turbo-rails-0.7.14/app/channels/turbo/streams/broadcasts.rb:38:in `broadcast_action_to'
15:59:32 web.1  | /Users/petter/.rvm/gems/ruby-3.0.2/gems/turbo-rails-0.7.14/app/jobs/turbo/streams/action_broadcast_job.rb:6:in `perform'
15:59:32 web.1  | /Users/petter/.rvm/gems/ruby-3.0.2/bundler/gems/rails-780753f571d2/activejob/lib/active_job/execution.rb:58:in `block in _perform_job'
15:59:32 web.1  | /Users/petter/.rvm/gems/ruby-3.0.2/bundler/gems/rails-780753f571d2/activesupport/lib/active_support/callbacks.rb:118:in `block in run_callbacks'
15:59:32 web.1  | /Users/petter/.rvm/gems/ruby-3.0.2/gems/i18n-1.8.10/lib/i18n.rb:314:in `with_locale'
15:59:32 web.1  | /Users/petter/.rvm/gems/ruby-3.0.2/bundler/gems/rails-780753f571d2/activejob/lib/active_job/translation.rb:9:in `block (2 levels) in <module:Translation>'
15:59:32 web.1  | /Users/petter/.rvm/gems/ruby-3.0.2/bundler/gems/rails-780753f571d2/activesupport/lib/active_support/callbacks.rb:127:in `instance_exec'
15:59:32 web.1  | /Users/petter/.rvm/gems/ruby-3.0.2/bundler/gems/rails-780753f571d2/activesupport/lib/active_support/callbacks.rb:127:in `block in run_callbacks'
15:59:32 web.1  | /Users/petter/.rvm/gems/ruby-3.0.2/bundler/gems/rails-780753f571d2/activesupport/lib/active_support/core_ext/time/zones.rb:66:in `use_zone'
15:59:32 web.1  | /Users/petter/.rvm/gems/ruby-3.0.2/bundler/gems/rails-780753f571d2/activejob/lib/active_job/timezones.rb:9:in `block (2 levels) in <module:Timezones>'
15:59:32 web.1  | /Users/petter/.rvm/gems/ruby-3.0.2/bundler/gems/rails-780753f571d2/activesupport/lib/active_support/callbacks.rb:127:in `instance_exec'
15:59:32 web.1  | /Users/petter/.rvm/gems/ruby-3.0.2/bundler/gems/rails-780753f571d2/activesupport/lib/active_support/callbacks.rb:127:in `block in run_callbacks'
15:59:32 web.1  | /Users/petter/.rvm/gems/ruby-3.0.2/bundler/gems/rails-780753f571d2/activesupport/lib/active_support/callbacks.rb:138:in `run_callbacks'
15:59:32 web.1  | /Users/petter/.rvm/gems/ruby-3.0.2/bundler/gems/rails-780753f571d2/activejob/lib/active_job/execution.rb:57:in `_perform_job'
15:59:32 web.1  | /Users/petter/.rvm/gems/ruby-3.0.2/bundler/gems/rails-780753f571d2/activejob/lib/active_job/instrumentation.rb:20:in `_perform_job'
15:59:32 web.1  | /Users/petter/.rvm/gems/ruby-3.0.2/bundler/gems/rails-780753f571d2/activejob/lib/active_job/execution.rb:46:in `perform_now'
15:59:32 web.1  | /Users/petter/.rvm/gems/ruby-3.0.2/bundler/gems/rails-780753f571d2/activejob/lib/active_job/instrumentation.rb:14:in `block in perform_now'
15:59:32 web.1  | /Users/petter/.rvm/gems/ruby-3.0.2/bundler/gems/rails-780753f571d2/activejob/lib/active_job/instrumentation.rb:25:in `block in instrument'
15:59:32 web.1  | /Users/petter/.rvm/gems/ruby-3.0.2/bundler/gems/rails-780753f571d2/activesupport/lib/active_support/notifications.rb:207:in `block in instrument'
15:59:32 web.1  | /Users/petter/.rvm/gems/ruby-3.0.2/bundler/gems/rails-780753f571d2/activesupport/lib/active_support/notifications/instrumenter.rb:24:in `instrument'
15:59:32 web.1  | /Users/petter/.rvm/gems/ruby-3.0.2/bundler/gems/rails-780753f571d2/activesupport/lib/active_support/notifications.rb:207:in `instrument'
15:59:32 web.1  | /Users/petter/.rvm/gems/ruby-3.0.2/bundler/gems/rails-780753f571d2/activejob/lib/active_job/instrumentation.rb:35:in `instrument'
15:59:32 web.1  | /Users/petter/.rvm/gems/ruby-3.0.2/bundler/gems/rails-780753f571d2/activejob/lib/active_job/instrumentation.rb:14:in `perform_now'
15:59:32 web.1  | /Users/petter/.rvm/gems/ruby-3.0.2/bundler/gems/rails-780753f571d2/activejob/lib/active_job/logging.rb:18:in `block in perform_now'
15:59:32 web.1  | /Users/petter/.rvm/gems/ruby-3.0.2/bundler/gems/rails-780753f571d2/activesupport/lib/active_support/tagged_logging.rb:99:in `block in tagged'
15:59:32 web.1  | /Users/petter/.rvm/gems/ruby-3.0.2/bundler/gems/rails-780753f571d2/activesupport/lib/active_support/tagged_logging.rb:37:in `tagged'
15:59:32 web.1  | /Users/petter/.rvm/gems/ruby-3.0.2/bundler/gems/rails-780753f571d2/activesupport/lib/active_support/tagged_logging.rb:99:in `tagged'
15:59:32 web.1  | /Users/petter/.rvm/gems/ruby-3.0.2/bundler/gems/rails-780753f571d2/activejob/lib/active_job/logging.rb:25:in `tag_logger'
15:59:32 web.1  | /Users/petter/.rvm/gems/ruby-3.0.2/bundler/gems/rails-780753f571d2/activejob/lib/active_job/logging.rb:18:in `perform_now'
15:59:32 web.1  | /Users/petter/.rvm/gems/ruby-3.0.2/bundler/gems/rails-780753f571d2/activejob/lib/active_job/execution.rb:24:in `block in execute'
15:59:32 web.1  | /Users/petter/.rvm/gems/ruby-3.0.2/bundler/gems/rails-780753f571d2/activesupport/lib/active_support/callbacks.rb:118:in `block in run_callbacks'
15:59:32 web.1  | /Users/petter/.rvm/gems/ruby-3.0.2/bundler/gems/rails-780753f571d2/activejob/lib/active_job/railtie.rb:54:in `block (4 levels) in <class:Railtie>'
15:59:32 web.1  | /Users/petter/.rvm/gems/ruby-3.0.2/bundler/gems/rails-780753f571d2/activesupport/lib/active_support/execution_wrapper.rb:88:in `wrap'
15:59:32 web.1  | /Users/petter/.rvm/gems/ruby-3.0.2/bundler/gems/rails-780753f571d2/activesupport/lib/active_support/reloader.rb:72:in `block in wrap'
15:59:32 web.1  | /Users/petter/.rvm/gems/ruby-3.0.2/bundler/gems/rails-780753f571d2/activesupport/lib/active_support/execution_wrapper.rb:88:in `wrap'
15:59:32 web.1  | /Users/petter/.rvm/gems/ruby-3.0.2/bundler/gems/rails-780753f571d2/activesupport/lib/active_support/reloader.rb:71:in `wrap'
15:59:32 web.1  | /Users/petter/.rvm/gems/ruby-3.0.2/bundler/gems/rails-780753f571d2/activejob/lib/active_job/railtie.rb:53:in `block (3 levels) in <class:Railtie>'
15:59:32 web.1  | /Users/petter/.rvm/gems/ruby-3.0.2/bundler/gems/rails-780753f571d2/activesupport/lib/active_support/callbacks.rb:127:in `instance_exec'
15:59:32 web.1  | /Users/petter/.rvm/gems/ruby-3.0.2/bundler/gems/rails-780753f571d2/activesupport/lib/active_support/callbacks.rb:127:in `block in run_callbacks'
15:59:32 web.1  | /Users/petter/.rvm/gems/ruby-3.0.2/bundler/gems/rails-780753f571d2/activesupport/lib/active_support/callbacks.rb:138:in `run_callbacks'
15:59:32 web.1  | /Users/petter/.rvm/gems/ruby-3.0.2/bundler/gems/rails-780753f571d2/activejob/lib/active_job/execution.rb:22:in `execute'
15:59:32 web.1  | /Users/petter/.rvm/gems/ruby-3.0.2/bundler/gems/rails-780753f571d2/activejob/lib/active_job/queue_adapters/async_adapter.rb:70:in `perform'
15:59:32 web.1  | /Users/petter/.rvm/gems/ruby-3.0.2/gems/concurrent-ruby-1.1.9/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:363:in `run_task'
15:59:32 web.1  | /Users/petter/.rvm/gems/ruby-3.0.2/gems/concurrent-ruby-1.1.9/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:352:in `block (3 levels) in create_worker'
15:59:32 web.1  | /Users/petter/.rvm/gems/ruby-3.0.2/gems/concurrent-ruby-1.1.9/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:335:in `loop'
15:59:32 web.1  | /Users/petter/.rvm/gems/ruby-3.0.2/gems/concurrent-ruby-1.1.9/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:335:in `block (2 levels) in create_worker'
15:59:32 web.1  | /Users/petter/.rvm/gems/ruby-3.0.2/gems/concurrent-ruby-1.1.9/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:334:in `catch'
15:59:32 web.1  | /Users/petter/.rvm/gems/ruby-3.0.2/gems/concurrent-ruby-1.1.9/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:334:in `block in create_worker'
```

**Comment by pettersj** [comment]
Closing this. Seems to work after bundle update today.
