### ISSUE TITLE
link_to does not invoke turbo_stream format in controller

### ISSUE THREAD

**Issue by blakeage** [hotwired/turbo-rails#453]
I just created a brand new Rails 7 app a couple weeks ago.  I'm using the gem turbo-rails (v1.4.0).  I can get form submissions to invoke the format.turbo_stream in the controller; however, links, no matter what I add to them, will not cause this format to be loaded.

Here is my link:
```<%= link_to "Cancel", cancel_force_schedule_expenditure_path(expenditure), remote: true, data: { "turbo-frame": dom_id(expenditure, 'force_schedule') }, class: "btn btn-light btn-sm border" %>```

This always invokes the controller via HTML, not Turbo Stream.  I've also tried without remote: true

I also tried this:
`<%= link_to "Cancel", cancel_force_schedule_expenditure_path(expenditure, format: :turbo_stream), remote: true, data: { "turbo-frame": dom_id(expenditure, 'force_schedule') }, class: "btn btn-light btn-sm border" %>`

...notice the addition to cancel_force_schedule_expenditure_path of format: :turbo_stream.  This causes the controller to respond correctly with the Turbo Stream; however, the browser redirects to a new page with the turbo stream code in the body (rather than Turbo handling the response and replacing the turbo frame).  This displays on the new page:
```<turbo-stream action="replace" target="force_schedule_expenditure_8"><template></template></turbo-stream>```

Here is my controller code:

```
def cancel_force_schedule
  respond_to do |format|
    format.turbo_stream{ render turbo_stream: turbo_stream.replace(dom_id(@expenditure, 'force_schedule')), partial: 'frequency_cell', locals: { expenditure: @expenditure } }
  end
end
```

application.js:
```
import "@hotwired/turbo-rails"
import "jquery"
import "@popperjs/core"
import "bootstrap"
import "flatpickr"
import "controllers"
```

The form containing the link:
```
<%= form_with url: force_schedule_expenditure_url( expenditure ), html: { data: { controller: "expenditures", "turbo-confirm": "Are you sure?", "turbo-frame": dom_id(expenditure, "force_schedule") }, class: "d-inline" } do |form| %>
  <div class="input-group input-group-sm d-inline-flex w-75">
    <label class="input-group-text">Details:</label>
    <label class="input-group-text">$</label>
    <%= form.text_field :amount, { placeholder: "Amount", value: @last_transaction&.amount, class: "form-control" } %>
    <%= form.text_field :pay_date, { placeholder: "Due Date", value: expenditure.bill_pay_date, class: "form-control", data: { controller: 'flatpickr', flatpickr: "{ dateFormat: 'Y-m-d' }" }} %>
    <%= link_to "Cancel", cancel_force_schedule_expenditure_path(expenditure), remote: true, data: { "turbo-frame": dom_id(expenditure, 'force_schedule') }, class: "btn btn-light btn-sm border" %>
    <%= form.submit "Schedule", class: "btn btn-primary btn-sm" %>
  </div>
<% end %>
```

The controller logs:
```
Started GET "/expenditures/8/cancel_force_schedule" for ::1 at 2023-04-11 19:10:47 -0400
Processing by ExpendituresController#cancel_force_schedule as HTML
  Parameters: {"id"=>"8"}
  User Load (0.3ms)  SELECT `users`.* FROM `users` WHERE `users`.`id` = 1 ORDER BY `users`.`id` ASC LIMIT 1
  ↳ app/controllers/expenditures_controller.rb:138:in `set_expenditure'
  Expenditure Load (0.2ms)  SELECT `expenditures`.* FROM `expenditures` WHERE `expenditures`.`user_id` = 1 AND `expenditures`.`id` = 8 ORDER BY `expenditures`.`name` ASC LIMIT 1
  ↳ app/controllers/expenditures_controller.rb:138:in `set_expenditure'
Completed 406 Not Acceptable in 5ms (ActiveRecord: 0.5ms | Allocations: 2476)
```

I'm not sure if I'm not setting something up right.  I've seen people recommend adding the format: :turbo_stream to the url helper in link_to, but for me, it always renders the turbo_stream code in a new page (it's not intercepted).  Any help is appreciated.

**Comment by blakeage** [comment]
Argh, I just realized I was missing the "turbo_stream: true" bit on the link_to.  It seems to work now.

The final link_to code:

`<%= link_to "Cancel", cancel_force_schedule_expenditure_path(expenditure), data: { turbo_stream: true, "turbo-frame": dom_id(expenditure, 'force_schedule') }, class: "btn btn-light btn-sm border" %>`
