### ISSUE TITLE
getting `Missing secret key base` during docker build when adding gem later

### ISSUE THREAD

**Issue by whysthatso** [hotwired/turbo-rails#459]
i'm seeing strange behavior when adding the gem to a rails app (rails 7.0.4.2, turbo-rails 1.4.0).

the rails app was initially started as `rails new app --minimal` and later i've added the things i needed.

docker builds have been working as expected up until i included this gem, after which builds break during this step:

```
[builder 11/13] RUN SECRET_KEY_BASE_DUMMY=1 bundle exec rails assets:precompile:
#0 3.715 rails aborted!
#0 3.715 ArgumentError: Missing `secret_key_base` for 'production' environment, set this string with `bin/rails credentials:edit`
```

it seems for some reason `SECRET_KEY_BASE_DUMMY=1` is ignored.

i had not build the app for a couple of commits, but i can confirm that once i took out the gem from the bundle, the build is successful again.

also, setting `SECRET_KEY_BASE=1` lets the build pass.

full stacktrace:
```
 > [builder 11/13] RUN SECRET_KEY_BASE_DUMMY=1 bundle exec rails assets:precompile:
#0 3.321 rails aborted!
#0 3.321 ArgumentError: Missing `secret_key_base` for 'production' environment, set this string with `bin/rails credentials:edit`
#0 3.321 /app/vendor/bundle/ruby/3.1.0/gems/railties-7.0.4.2/lib/rails/application.rb:581:in `validate_secret_key_base'
#0 3.321 /app/vendor/bundle/ruby/3.1.0/gems/railties-7.0.4.2/lib/rails/application.rb:419:in `secret_key_base'
#0 3.321 /app/vendor/bundle/ruby/3.1.0/gems/railties-7.0.4.2/lib/rails/application.rb:157:in `key_generator'
#0 3.321 /app/vendor/bundle/ruby/3.1.0/gems/turbo-rails-1.4.0/lib/turbo/engine.rb:66:in `block (2 levels) in <class:Engine>'
#0 3.321 /app/vendor/bundle/ruby/3.1.0/gems/activesupport-7.0.4.2/lib/active_support/lazy_load_hooks.rb:92:in `block in execute_hook'
#0 3.321 /app/vendor/bundle/ruby/3.1.0/gems/activesupport-7.0.4.2/lib/active_support/lazy_load_hooks.rb:85:in `with_execution_control'
#0 3.321 /app/vendor/bundle/ruby/3.1.0/gems/activesupport-7.0.4.2/lib/active_support/lazy_load_hooks.rb:90:in `execute_hook'
#0 3.321 /app/vendor/bundle/ruby/3.1.0/gems/activesupport-7.0.4.2/lib/active_support/lazy_load_hooks.rb:76:in `block in run_load_hooks'
#0 3.321 /app/vendor/bundle/ruby/3.1.0/gems/activesupport-7.0.4.2/lib/active_support/lazy_load_hooks.rb:75:in `each'
#0 3.321 /app/vendor/bundle/ruby/3.1.0/gems/activesupport-7.0.4.2/lib/active_support/lazy_load_hooks.rb:75:in `run_load_hooks'
#0 3.321 /app/vendor/bundle/ruby/3.1.0/gems/railties-7.0.4.2/lib/rails/application/finisher.rb:87:in `block in <module:Finisher>'
#0 3.321 /app/vendor/bundle/ruby/3.1.0/gems/railties-7.0.4.2/lib/rails/initializable.rb:32:in `instance_exec'
#0 3.321 /app/vendor/bundle/ruby/3.1.0/gems/railties-7.0.4.2/lib/rails/initializable.rb:32:in `run'
#0 3.321 /app/vendor/bundle/ruby/3.1.0/gems/railties-7.0.4.2/lib/rails/initializable.rb:61:in `block in run_initializers'
#0 3.321 /app/vendor/bundle/ruby/3.1.0/gems/railties-7.0.4.2/lib/rails/initializable.rb:60:in `run_initializers'
#0 3.321 /app/vendor/bundle/ruby/3.1.0/gems/railties-7.0.4.2/lib/rails/application.rb:372:in `initialize!'
#0 3.321 /app/config/environment.rb:5:in `<top (required)>'
#0 3.321 /app/vendor/bundle/ruby/3.1.0/gems/zeitwerk-2.6.7/lib/zeitwerk/kernel.rb:38:in `require'
#0 3.321 /app/vendor/bundle/ruby/3.1.0/gems/zeitwerk-2.6.7/lib/zeitwerk/kernel.rb:38:in `require'
#0 3.321 /app/vendor/bundle/ruby/3.1.0/gems/railties-7.0.4.2/lib/rails/application.rb:348:in `require_environment!'
#0 3.321 /app/vendor/bundle/ruby/3.1.0/gems/railties-7.0.4.2/lib/rails/application.rb:511:in `block in run_tasks_blocks'
#0 3.321 /app/vendor/bundle/ruby/3.1.0/gems/rake-13.0.6/lib/rake/task.rb:281:in `block in execute'
#0 3.321 /app/vendor/bundle/ruby/3.1.0/gems/rake-13.0.6/lib/rake/task.rb:281:in `each'
#0 3.321 /app/vendor/bundle/ruby/3.1.0/gems/rake-13.0.6/lib/rake/task.rb:281:in `execute'
#0 3.321 /app/vendor/bundle/ruby/3.1.0/gems/rake-13.0.6/lib/rake/task.rb:219:in `block in invoke_with_call_chain'
#0 3.321 /app/vendor/bundle/ruby/3.1.0/gems/rake-13.0.6/lib/rake/task.rb:199:in `synchronize'
#0 3.321 /app/vendor/bundle/ruby/3.1.0/gems/rake-13.0.6/lib/rake/task.rb:199:in `invoke_with_call_chain'
#0 3.321 /app/vendor/bundle/ruby/3.1.0/gems/rake-13.0.6/lib/rake/task.rb:243:in `block in invoke_prerequisites'
#0 3.321 /app/vendor/bundle/ruby/3.1.0/gems/rake-13.0.6/lib/rake/task.rb:241:in `each'
#0 3.321 /app/vendor/bundle/ruby/3.1.0/gems/rake-13.0.6/lib/rake/task.rb:241:in `invoke_prerequisites'
#0 3.321 /app/vendor/bundle/ruby/3.1.0/gems/rake-13.0.6/lib/rake/task.rb:218:in `block in invoke_with_call_chain'
#0 3.321 /app/vendor/bundle/ruby/3.1.0/gems/rake-13.0.6/lib/rake/task.rb:199:in `synchronize'
#0 3.321 /app/vendor/bundle/ruby/3.1.0/gems/rake-13.0.6/lib/rake/task.rb:199:in `invoke_with_call_chain'
#0 3.321 /app/vendor/bundle/ruby/3.1.0/gems/rake-13.0.6/lib/rake/task.rb:188:in `invoke'
#0 3.321 /app/vendor/bundle/ruby/3.1.0/gems/rake-13.0.6/lib/rake/application.rb:160:in `invoke_task'
#0 3.321 /app/vendor/bundle/ruby/3.1.0/gems/rake-13.0.6/lib/rake/application.rb:116:in `block (2 levels) in top_level'
#0 3.321 /app/vendor/bundle/ruby/3.1.0/gems/rake-13.0.6/lib/rake/application.rb:116:in `each'
#0 3.321 /app/vendor/bundle/ruby/3.1.0/gems/rake-13.0.6/lib/rake/application.rb:116:in `block in top_level'
#0 3.321 /app/vendor/bundle/ruby/3.1.0/gems/rake-13.0.6/lib/rake/application.rb:125:in `run_with_threads'
#0 3.321 /app/vendor/bundle/ruby/3.1.0/gems/rake-13.0.6/lib/rake/application.rb:110:in `top_level'
#0 3.321 /app/vendor/bundle/ruby/3.1.0/gems/railties-7.0.4.2/lib/rails/commands/rake/rake_command.rb:24:in `block (2 levels) in perform'
#0 3.321 /app/vendor/bundle/ruby/3.1.0/gems/rake-13.0.6/lib/rake/application.rb:186:in `standard_exception_handling'
#0 3.321 /app/vendor/bundle/ruby/3.1.0/gems/railties-7.0.4.2/lib/rails/commands/rake/rake_command.rb:24:in `block in perform'
#0 3.321 /app/vendor/bundle/ruby/3.1.0/gems/rake-13.0.6/lib/rake/rake_module.rb:59:in `with_application'
#0 3.321 /app/vendor/bundle/ruby/3.1.0/gems/railties-7.0.4.2/lib/rails/commands/rake/rake_command.rb:18:in `perform'
#0 3.321 /app/vendor/bundle/ruby/3.1.0/gems/railties-7.0.4.2/lib/rails/command.rb:51:in `invoke'
#0 3.321 /app/vendor/bundle/ruby/3.1.0/gems/railties-7.0.4.2/lib/rails/commands.rb:18:in `<top (required)>'
#0 3.321 Tasks: TOP => assets:precompile => environment
```

**Comment by bjufre** [comment]
This is an issue for our application as well, everything was working smoothly for our Docker builds, until we've added this gem. We solved it by adding the dummy `SECRET_KEY_BASE` but that doesn't really feel like it should be handled this way. Is there anything that we can do in order to fix this upstream?

**Comment by brunoprietog** [comment]
Hello, this is not a Turbo issue. I recommend checking the default Dockerfile that Rails includes in new applications, where it works perfectly.
