### ISSUE TITLE
Including `tubo_rails` gem breaks `normalize_name'

### ISSUE THREAD

**Issue by firedev** [hotwired/turbo-rails#468]
Hi, 

Adding `turbo-rails`, `-> 1.4` to our `Rails 6.0.5` app caused this error in tests:

```
NoMethodError:
       Could not render layout: undefined method `empty?' for nil:NilClass
/lib/action_view/lookup_context.rb:234:in `normalize_name'
```

```
context "when the controller's action does not respond to formats" do
  controller do
    def index; end
  end

  let(:format) { :hello }

  it 'raises an UnknownFormat' do
    expect {
	  get :index, format: format
	}.to raise_error(ActionController::UnknownFormat)
  end
```

It fails here:

```
actionview-6.0.6.1/lib/action_view/lookup_context.rb:234:in `normalize_name'",
actionview-6.0.6.1/lib/action_view/lookup_context.rb:183:in `args_for_lookup'",
actionview-6.0.6.1/lib/action_view/lookup_context.rb:139:in `find_all'",
actionview-6.0.6.1/lib/action_view/layouts.rb:327:in `_layout'",
actionview-6.0.6.1/lib/action_view/layouts.rb:413:in `_default_layout'",
actionview-6.0.6.1/lib/action_view/layouts.rb:389:in `block in _layout_for_option'",
actionview-6.0.6.1/lib/action_view/renderer/template_renderer.rb:101:in `resolve_layout'",
actionview-6.0.6.1/lib/action_view/renderer/template_renderer.rb:80:in `find_layout'",
actionview-6.0.6.1/lib/action_view/renderer/template_renderer.rb:64:in `render_with_layout'",
actionview-6.0.6.1/lib/action_view/renderer/template_renderer.rb:56:in `render_template'",
actionview-6.0.6.1/lib/action_view/renderer/template_renderer.rb:13:in `render'",
actionview-6.0.6.1/lib/action_view/renderer/renderer.rb:61:in `render_template_to_object'",
actionview-6.0.6.1/lib/action_view/renderer/renderer.rb:29:in `render_to_object'",
actionview-6.0.6.1/lib/action_view/rendering.rb:117:in `block in _render_template'",
actionview-6.0.6.1/lib/action_view/base.rb:304:in `in_rendering_context'",
actionview-6.0.6.1/lib/action_view/rendering.rb:116:in `_render_template'",
actionpack-6.0.6.1/lib/action_controller/metal/streaming.rb:218:in `_render_template'",
actionview-6.0.6.1/lib/action_view/rendering.rb:103:in `render_to_body'",
actionpack-6.0.6.1/lib/action_controller/metal/rendering.rb:52:in `render_to_body'",
actionpack-6.0.6.1/lib/action_controller/metal/renderers.rb:142:in `render_to_body'",
actionpack-6.0.6.1/lib/abstract_controller/rendering.rb:25:in `render'",
actionpack-6.0.6.1/lib/action_controller/metal/rendering.rb:36:in `render'",
actionpack-6.0.6.1/lib/action_controller/metal/instrumentation.rb:44:in `block (2 levels) in render'",
activesupport-6.0.6.1/lib/active_support/core_ext/benchmark.rb:14:in `block in ms'",
2.7.8/lib/ruby/2.7.0/benchmark.rb:308:in `realtime'",
activesupport-6.0.6.1/lib/active_support/core_ext/benchmark.rb:14:in `ms'",
actionpack-6.0.6.1/lib/action_controller/metal/instrumentation.rb:44:in `block in render'",
actionpack-6.0.6.1/lib/action_controller/metal/instrumentation.rb:84:in `cleanup_view_runtime'",
activerecord-6.0.6.1/lib/active_record/railties/controller_runtime.rb:34:in `cleanup_view_runtime'",
actionpack-6.0.6.1/lib/action_controller/metal/instrumentation.rb:43:in `render'",
wicked_pdf-2.6.3/lib/wicked_pdf/pdf_helper.rb:18:in `render'",
```

The error is caused by `normalize_name` being called with an empty string instead of `"application"`. I can solve it by patching `ViewPaths` like this: 

```
module ActionView
  class LookupContext
    module ViewPaths
      def normalize_name(name, prefixes)
        name = "application" if name == "" # <- "Fix"
		...
   	  end
    end
  end
end
```

Does this ring any bells? It's too much metaprogramming I can't figure out what is going on.

**Comment by firedev** [comment]
Okay the default `layout` is gone it seems, so adding `layout "application"` in tests fixed it. Also https://github.com/hotwired/turbo-rails/issues/268
