### ISSUE TITLE
Chromedriver gets a stale reference after the `body` is replaced

### ISSUE THREAD

**Issue by diazruy** [hotwired/turbo-rails#471]
Adding Turbo to my existing RoR 6.1.7.3 application, everything seems to work great. However, when I run my system tests (RSpec +  Capybara, Selenium and headless chrome), it appears that any call to `page` once the `body` has been replaced causes a

```
     Selenium::WebDriver::Error::StaleElementReferenceError:
       stale element reference: stale element not found
```

My gem versions:
- `rspec-core`: 3.12.2
- `selenium-webdriver`: 4.9.1
- `webdrivers`: 5.2.0
- `capybara`: 3.39.1
- `turbo-rails`: 1.4.0

The relevant part of the test is

```ruby
      find('input[type="submit"]').click
      expect(page).to have_content('Sent an invitation')
```
Test output is
```
     Failure/Error: expect(page).to have_content('Sent an invitation')
     
     Selenium::WebDriver::Error::StaleElementReferenceError:
       stale element reference: stale element not found
         (Session info: headless chrome=113.0.5672.126)
     
     # 0   chromedriver                        0x00000001052bb8ac chromedriver + 4257964
     # 1   chromedriver                        0x00000001052b3f40 chromedriver + 4226880
     # 2   chromedriver                        0x0000000104ef09d4 chromedriver + 281044
     # 3   chromedriver                        0x0000000104ef5200 chromedriver + 299520
     # 4   chromedriver                        0x0000000104ef6b34 chromedriver + 305972
     # 5   chromedriver                        0x0000000104ef6c24 chromedriver + 306212
     # 6   chromedriver                        0x0000000104f2b718 chromedriver + 522008
     # 7   chromedriver                        0x0000000104f211cc chromedriver + 479692
     # 8   chromedriver                        0x0000000104f627e4 chromedriver + 747492
     # 9   chromedriver                        0x0000000104f1f98c chromedriver + 473484
     # 10  chromedriver                        0x0000000104f2098c chromedriver + 477580
     # 11  chromedriver                        0x000000010527a900 chromedriver + 3991808
     # 12  chromedriver                        0x000000010527e354 chromedriver + 4006740
     # 13  chromedriver                        0x000000010527e940 chromedriver + 4008256
     # 14  chromedriver                        0x000000010528433c chromedriver + 4031292
     # 15  chromedriver                        0x000000010527ef34 chromedriver + 4009780
     # 16  chromedriver                        0x0000000105257490 chromedriver + 3847312
     # 17  chromedriver                        0x000000010529c9f4 chromedriver + 4131316
     # 18  chromedriver                        0x000000010529cb4c chromedriver + 4131660
     # 19  chromedriver                        0x00000001052ad230 chromedriver + 4198960
     # 20  libsystem_pthread.dylib             0x0000000189593fa8 _pthread_start + 148
     # 21  libsystem_pthread.dylib             0x000000018958eda0 thread_start + 8
     # ./spec/system/invite_teammates_spec.rb:21:in `block (3 levels) in <top (required)>'
     # ./spec/system/invite_teammates_spec.rb:18:in `block (2 levels) in <top (required)>'
```

My guess is that the replacement of the `<body>` node in the DOM by a new one is causing Selenium to lose track/access to the referenced element and does not "reattach itself" to the new one somehow.

**Comment by diazruy** [comment]
Hold the phone...

Turns out the problem wasn't really the `body` replacement after all. The actual issue was that my `find`/`expect`	 were inside a `within` block, and due to the replacement of the body, the element originally referenced by the `within` was now gone. When I move the `expect(page)` _out_ of the `within`, everything works
```ruby
   # Before
    within find(some_selector) do
      find('input[type="submit"]').click
     # element referenced by `find(some_selector)` is now gone from the DOM
      expect(page).to have_text('Sent an invitation')
    end
```
```ruby
   # After
    within find(some_selector) do
      find('input[type="submit"]').click
    end
    expect(page).to have_text('Sent an invitation')
```
