### ISSUE TITLE
Issue with render_to_string method of ActionController. "Could not render layout: undefined method `headers`"

### ISSUE THREAD

**Issue by limjinsun** [hotwired/turbo-rails#529]
```
Ruby version 3.2.2
Rails version 7.0.8
```
GemFile
```
source 'https://rubygems.org'

ruby '3.2.2'

gem 'rails', '7.0.8'
gem 'puma', '~> 4.3.9'
gem 'sass-rails', '~>6.0.0'
gem 'jquery-rails'
gem 'sprockets', '3.7.2'

# gem 'bootstrap', '~> 5.1.3'

gem 'sprockets-rails'
gem 'turbo-rails'
gem 'stimulus-rails'
gem 'hotwire-rails'
gem 'importmap-rails'
gem 'jsbundling-rails'

gem 'jbuilder', '~> 2.5'
gem 'twilio-ruby', '5.72.1'
gem 'google-authenticator-rails'
gem 'friendly_id', '~> 5.2.0'
gem 'mysql2'

...
```

Error.
```
irb(main):003:0> ActionController::Base.new.render_to_string( template: "shared/file_template/test2" )
/Users/xxx/Documents/projects/rails-project/vendor/cache/ruby/3.2.0/gems/turbo-rails-1.5.0/app/controllers/turbo/frames/frame_request.rb:36:in `turbo_frame_request_id': Could not render layout: undefined method `headers' for nil:NilClass (NoMethodError)

      request.headers["Turbo-Frame"]
             ^^^^^^^^
/Users/xxx/Documents/projects/rails-project/vendor/cache/ruby/3.2.0/gems/turbo-rails-1.5.0/app/controllers/turbo/frames/frame_request.rb:36:in `turbo_frame_request_id': undefined method `headers' for nil:NilClass (NoMethodError)

      request.headers["Turbo-Frame"]
             ^^^^^^^^
```

**Comment by brunoprietog** [comment]
I've opened #532 to solve this

**Comment by ryanckulp** [comment]
i have the same problem. perhaps `&.` isn't the best solution, but if there's a way to pass in a `request` object to `render_to_string` then we're all set.

**Comment by ryanckulp** [comment]
hey @brunoprietog , a simple solution i found is to simply pass in an empty Request object:

```rb
ac = ActionController::Base.new
ac.request = ActionDispatch::Request.new({})
ac.render_to_string(template: 'view/partial', locals: { variable: 'here' }, layout: 'application')

# => renders HTML string
```
