### ISSUE TITLE
Release for the routes warning

### ISSUE THREAD

**Issue by dorianmariecom** [hotwired/turbo-rails#671]
I see it's fixed in main/master

```
DEPRECATION WARNING: Drawing a route with a hash key name is deprecated and will be removed in Rails 8.1. Please use the `to:` option with "controller#action" syntax instead. Instead of: match "path" => "controller#action` Please use: match "path", to: "controller#action" (called from <top (required)> at /Users/dorianmariefr/src/dorianmariecom/code/config/environment.rb:7)
/Users/dorianmariefr/.asdf/installs/ruby/3.3.4/lib/ruby/gems/3.3.0/bundler/gems/rails-c6e3336cfdec/actionpack/lib/action_dispatch/routing/mapper.rb:798:in `map_method'
  /Users/dorianmariefr/.asdf/installs/ruby/3.3.4/lib/ruby/gems/3.3.0/bundler/gems/rails-c6e3336cfdec/actionpack/lib/action_dispatch/routing/mapper.rb:741:in `get'
  /Users/dorianmariefr/.asdf/installs/ruby/3.3.4/lib/ruby/gems/3.3.0/gems/turbo-rails-2.0.6/config/routes.rb:3:in `block in <top (required)>'
  /Users/dorianmariefr/.asdf/installs/ruby/3.3.4/lib/ruby/gems/3.3.0/bundler/gems/rails-c6e3336cfdec/actionpack/lib/action_dispatch/routing/route_set.rb:479:in `instance_exec'
  /Users/dorianmariefr/.asdf/installs/ruby/3.3.4/lib/ruby/gems/3.3.0/bundler/gems/rails-c6e3336cfdec/actionpack/lib/action_dispatch/routing/route_set.rb:479:in `eval_block'
  /Users/dorianmariefr/.asdf/installs/ruby/3.3.4/lib/ruby/gems/3.3.0/bundler/gems/rails-c6e3336cfdec/actionpack/lib/action_dispatch/routing/route_set.rb:461:in `draw'
  /Users/dorianmariefr/.asdf/installs/ruby/3.3.4/lib/ruby/gems/3.3.0/gems/turbo-rails-2.0.6/config/routes.rb:1:in `<top (required)>'
  /Users/dorianmariefr/.asdf/installs/ruby/3.3.4/lib/ruby/gems/3.3.0/bundler/gems/rails-c6e3336cfdec/railties/lib/rails/application/routes_reloader.rb:60:in `load'
  /Users/dorianmariefr/.asdf/installs/ruby/3.3.4/lib/ruby/gems/3.3.0/bundler/gems/rails-c6e3336cfdec/railties/lib/rails/application/routes_reloader.rb:60:in `block in load_paths'
  /Users/dorianmariefr/.asdf/installs/ruby/3.3.4/lib/ruby/gems/3.3.0/bundler/gems/rails-c6e3336cfdec/railties/lib/rails/application/routes_reloader.rb:60:in `each'
  /Users/dorianmariefr/.asdf/installs/ruby/3.3.4/lib/ruby/gems/3.3.0/bundler/gems/rails-c6e3336cfdec/railties/lib/rails/application/routes_reloader.rb:60:in `load_paths'
  /Users/dorianmariefr/.asdf/installs/ruby/3.3.4/lib/ruby/gems/3.3.0/bundler/gems/rails-c6e3336cfdec/railties/lib/rails/application/routes_reloader.rb:26:in `reload!'
  /Users/dorianmariefr/.asdf/installs/ruby/3.3.4/lib/ruby/gems/3.3.0/bundler/gems/rails-c6e3336cfdec/railties/lib/rails/application/routes_reloader.rb:48:in `block in updater'
  /Users/dorianmariefr/.asdf/installs/ruby/3.3.4/lib/ruby/gems/3.3.0/bundler/gems/rails-c6e3336cfdec/activesupport/lib/active_support/file_update_checker.rb:85:in `execute'
  /Users/dorianmariefr/.asdf/installs/ruby/3.3.4/lib/ruby/gems/3.3.0/bundler/gems/rails-c6e3336cfdec/railties/lib/rails/application/routes_reloader.rb:13:in `execute'
  /Users/dorianmariefr/.asdf/installs/ruby/3.3.4/lib/ruby/gems/3.3.0/bundler/gems/rails-c6e3336cfdec/railties/lib/rails/application/routes_reloader.rb:35:in `execute_unless_loaded'
  /Users/dorianmariefr/.asdf/installs/ruby/3.3.4/lib/ruby/gems/3.3.0/bundler/gems/rails-c6e3336cfdec/railties/lib/rails/application/finisher.rb:180:in `block in <module:Finisher>'
  /Users/dorianmariefr/.asdf/installs/ruby/3.3.4/lib/ruby/gems/3.3.0/bundler/gems/rails-c6e3336cfdec/railties/lib/rails/initializable.rb:32:in `instance_exec'
  /Users/dorianmariefr/.asdf/installs/ruby/3.3.4/lib/ruby/gems/3.3.0/bundler/gems/rails-c6e3336cfdec/railties/lib/rails/initializable.rb:32:in `run'
  /Users/dorianmariefr/.asdf/installs/ruby/3.3.4/lib/ruby/gems/3.3.0/bundler/gems/rails-c6e3336cfdec/railties/lib/rails/initializable.rb:61:in `block in run_initializers'
  /Users/dorianmariefr/.asdf/installs/ruby/3.3.4/lib/ruby/3.3.0/tsort.rb:231:in `block in tsort_each'
```

**Comment by dhh** [comment]
This deprecation has been removed from Rails.
